spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

security.token.secret=JAVAGAS_@123#
security.token.secret.candidate=JAVAGAS_CANDIDATE_@123#

token.sonar = sqp_6f86e56fed59d37488704bccc542cd6159a5cc08